### PR TITLE
docs(core): update readme with local setup instructions

### PR DESCRIPTION
**Pull request by dblanken-yale**
Creates initial documentation for setup in a local Linux/MacOS environment with easily copyable command line instructions.

See readme on the repository's branch page: https://github.com/Yale-A11y/e2e-a11y-testing/tree/6-doc-score-update-readme-with-local-setup-instructions

### Acceptance criteria:
- [ ] Installation steps work when following them
- [ ] Grammar and spelling are acceptable

### CODE REVIEW

**Review by myvaughn — APPROVED** [review]
Looks good to me for now. For the purposes of sharing this with other web teams, I wonder if our reliance on pnpm is going to confuse developers who don't know about it. Future revisions of this file should make it clear that these are example scripts, along with more fleshed out explanation of what's going on, and how teams could deploy a similar testing approach in their own project (like if using npm or yarn, for example).

**Comment by dblanken-yale** [comment]
I can easily add npm instructions as well.  Think that would help?  The only issue would be we'd need to maintain both pnpm's lock file and npm's lock file to ensure they're the same.  Or we start pinning our packages.json now to ensure any fresh pulls pull the right version--could mean more dependency maintenance in the long run.

**Comment by myvaughn** [comment]
@dblanken-yale I guess it would make sense to add instructions for npm and maybe even yarn. There's no risk for people outside our team since they're not going to push changes to our repo, so as long as we enforce use of pnpm for contributors it should be ok.

**Comment by dblanken-yale** [comment]
I added `yarn/npm` instructions; let me know what you think.

**Review by myvaughn — APPROVED** [review]
Looks good.

**Comment by dblanken-yale** [comment]
Per conversation with @myvaughn, I reverted the docs to using `npm`.  Others will work, but for the sake of documentation simplicity, the others are removed.

**Review by myvaughn — APPROVED** [review]
Looks good. Let's merge it.

**Pull request merged**
